services:
  packetx-db:
    image: postgres:17
    container_name: packetx-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - packetx-db:/var/lib/postgresql/data

  adminer:
    image: adminer:5
    container_name: packetx-adminer
    restart: unless-stopped
    ports:
      - '800:8080'

volumes:
  packetx-db:
    name: packetx-db